// generated by adlc-skills-cli; source: adlc-events — do not edit
import type { Plugin } from "@opencode-ai/plugin"
import { execFileSync } from "node:child_process"
import { resolve } from "node:path"
import { statSync } from "node:fs"

let DISPATCHER = ""
let SKILLS_DIR = ".agents/skills"

// Cache for session_start handlers — experimental.chat.messages.transform
// fires on every step, but the script output is stable for the session.
// Keyed by skill name so multiple session_start handlers each get their own cache.
const _sessionStartCache: Record<string, string> = {}

// Track init-options.json state so the cache invalidates when team-setup
// creates/modifies/deletes the config (e.g., unconfigured → configured).
let _sessionStartState: { exists: boolean; mtime: number } = { exists: false, mtime: 0 }

function runEvent(command: string, event: string, timeoutSec: number): string {
  try {
    const result = execFileSync("node", [DISPATCHER, event, command, SKILLS_DIR, String(timeoutSec)], {
      input: "",
      encoding: "utf-8",
      timeout: (timeoutSec + 5) * 1000,
    })
    return result
  } catch (e) {
    throw new Error("adlc event " + command + " (" + event + ") failed: " + (e as Error).message)
  }
}

export const AdlcEventsPlugin: Plugin = async ({ directory }) => {
  DISPATCHER = resolve(directory, ".agents", "dispatcher.mjs")
  return {
    "experimental.chat.messages.transform": async (_input, output) => {
      try {
        // Invalidate cache when .adlc/init-options.json changes (team-setup ran)
        let _exists = false, _mtime = 0
        try { const st = statSync(".adlc/init-options.json"); _exists = true; _mtime = st.mtimeMs } catch {}
        const _stateChanged = _exists !== _sessionStartState.exists || _mtime !== _sessionStartState.mtime
        if (_stateChanged) {
          for (const k of Object.keys(_sessionStartCache)) delete _sessionStartCache[k]
          _sessionStartState = { exists: _exists, mtime: _mtime }
        }
        const _key = "team-boot"
        if (!(_key in _sessionStartCache)) {
          _sessionStartCache[_key] = runEvent(_key, "session_start", 60)
        }
        const ctx = _sessionStartCache[_key]
        if (!ctx) return
        // Inject into first user message (active instructions, not passive system prompt)
        const firstUser = output.messages.find((m: any) => m.info.role === 'user')
        if (!firstUser || !firstUser.parts.length) return
        // Guard: skip if already injected (prevents double-injection on step re-fires)
        if (firstUser.parts.some((p: any) => p.type === 'text' && p.text.includes('EXTREMELY_IMPORTANT'))) return
        const ref = firstUser.parts[0]
        firstUser.parts.unshift({ ...ref, type: 'text', text: ctx })
      } catch (e) {
        console.error("adlc messages.transform hook failed:", (e as Error).message)
      }
    }
  }
}
